[package]
name = "rpg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ggez = "0.5"
ggez = { git = "https://github.com/ggez/ggez", branch = "devel" }
rand = "0.8"
